service:
  name: youtube-google-oauth-api
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:NODE_ENV} # Set the default stage used. Default is dev
  region: ap-northeast-2 # Overwrite the default region used. Default is us-east-1
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  environment:
    NODE_ENV: ${self:provider.stage}
    NODE_PATH: ${env:NODE_ENV}
  deploymentBucket:
    name: youtube-google-oauth-api.sls.${self:provider.stage} # Overwrite the default deployment bucket
    serverSideEncryption: AES256 # when using server-side encryption

functions: ${file(./config/handlers.yml)}