service:
  name: youtube-google-oauth-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:NODE_ENV} # Set the default stage used. Default is dev
  region: ap-northeast-2 # Overwrite the default region used. Default is us-east-1
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  environment:
    NODE_ENV: ${self:provider.stage}
    NODE_PATH: ${env:NODE_PATH}
    API_HOST: ${env:API_HOST}
    DATASOURCE_PG_HOST: ${env:DATASOURCE_PG_HOST}
    DATASOURCE_PG_PORT: ${env:DATASOURCE_PG_PORT}
    DATASOURCE_PG_USERNAME: ${env:DATASOURCE_PG_USERNAME}
    DATASOURCE_PG_PASSWORD: ${env:DATASOURCE_PG_PASSWORD}
    DATASOURCE_PG_DATABASE: ${env:DATASOURCE_PG_DATABASE}

    GOOGLE_OAUTH2_ENDPOINT: ${env:GOOGLE_OAUTH2_ENDPOINT}
    GOOGLE_OAUTH2_ENDPOINT_GET_TOKEN: ${env:GOOGLE_OAUTH2_ENDPOINT_GET_TOKEN}
    GOOGLE_OAUTH2_CLIENT_ID: ${env:GOOGLE_OAUTH2_CLIENT_ID}
    GOOGLE_OAUTH2_CLIENT_SECRET: ${env:GOOGLE_OAUTH2_CLIENT_SECRET}

  deploymentBucket:
    name: youtube-google-oauth-api.sls.${self:provider.stage} # Overwrite the default deployment bucket
    serverSideEncryption: AES256 # when using server-side encryption

functions: ${file(./config/handlers.yml)}