ssr:
  handler: src/handler.api
  events:
    - http:
        path: /
        method: GET
    - http:
        path: /{proxy+}
        method: ANY
    - http:
        path: /{proxy+}
        method: OPTIONS

